pathInfo:
  protDir: "/home/esp/Machine_Learning/12_cofactorID_III/01_pocket_pdbs"
  ligandDir: "/home/esp/scriptDevelopment/pocketDock/ligands"
  outDir: "/home/esp/scriptDevelopment/pocketDock/outputs"
  dockingOrdersYaml: "/home/esp/scriptDevelopment/pocketDock/docking_orders.yaml"
generalInfo:
  fpocketInputs: True
dockingInfo:
  maxFlexRes: 0
  nCoresPerRun: 1
  totalCpus: 32
  exhaustiveness: 4
  numModes: 8
cleanUpInfo:
  collateOutputs: True
  genDockingReport: True
  removeRunDirs: True