pathInfo:
  protDir: "/home/esp/scriptDevelopment/pocketDock/receptors"
  ligandDir: "/home/esp/scriptDevelopment/pocketDock/ligands"
  outDir: "/home/esp/scriptDevelopment/pocketDock/outputs"
  dockingOrdersYaml: "/home/esp/scriptDevelopment/pocketDock/docking_orders.yaml"
generalInfo:
  fpocketInputs: True
dockingInfo:
  maxFlexRes: 10
  nCoresPerRun: 16
  totalCpus: 1
  exhaustiveness: 16
  numModes: 10
cleanUpInfo:
  collateOutputs: True
  genDockingReport: False
  removeRunDirs: False